# Generated by Django 5.0.6 on 2024-09-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_storedetails_latitude_storedetails_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.storedetails')),
            ],
        ),
    ]
