# Generated by Django 5.0.6 on 2024-08-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_storedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_count', models.PositiveIntegerField(default=0)),
                ('abandoned_cart_count', models.PositiveIntegerField(default=0)),
                ('cart_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StoreRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StoreVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_count', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile')),
            ],
        ),
    ]
