# Generated by Django 5.2 on 2025-05-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecart',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile'),
        ),
        migrations.AddField(
            model_name='storerevenue',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile'),
        ),
        migrations.AddField(
            model_name='storevisitor',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile'),
        ),
        migrations.AddField(
            model_name='visitorpurchase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile'),
        ),
    ]
