# Generated by Django 5.2 on 2025-05-05 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='stores.storedetails'),
        ),
        migrations.AddField(
            model_name='savedstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storereview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.storedetails'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='savedproduct',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='savedstore',
            unique_together={('user', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='storereview',
            unique_together={('user', 'store')},
        ),
    ]
