# Generated by Django 5.1.6 on 2025-02-11 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='0000000000', max_length=20, null=True)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('rider_id', models.CharField(blank=True, max_length=12, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
