# Generated by Django 5.0.6 on 2024-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrider',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchrider',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=20, null=True),
        ),
    ]
