# Generated by Django 5.0.6 on 2024-10-25 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchrider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dispatchrider',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='dispatchrider',
            name='password',
        ),
        migrations.AddField(
            model_name='dispatchrider',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
