# Generated by Django 5.2 on 2025-05-05 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='store_user_profiles', related_query_name='store_user_profile', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='store_user_permissions_profiles', related_query_name='store_user_profile', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cac_image', models.ImageField(upload_to='cac_images/')),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('appliances', 'Appliances'), ('household_cleaning', 'Household Cleaning'), ('electronics', 'Electronics'), ('other', 'Other Category')], default='other', max_length=50)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('about_store', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='store_profiles/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='store_backgrounds/')),
                ('store_user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_details', to='stores.storeuserprofile')),
            ],
        ),
    ]
