# Generated by Django 5.2 on 2025-05-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedetails',
            name='category',
        ),
    ]
