# Generated by Django 5.1.6 on 2025-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedetails',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('appliances', 'Appliances'), ('household_cleaning', 'Household Cleaning'), ('electronics', 'Electronics'), ('other', 'Other Category')], default='other', max_length=50),
        ),
    ]
