# Generated by Django 5.0.6 on 2024-08-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_storeuserprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('store_address', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cac_image', models.ImageField(upload_to='cac_images/')),
                ('store_user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.storeuserprofile')),
            ],
        ),
    ]
