# Generated by Django 5.0.6 on 2024-09-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storedetails_about_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedetails',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedetails',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
