# Generated by Django 5.0.6 on 2024-12-18 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storedetails_latitude_storedetails_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedetails',
            name='store_user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_details', to='stores.storeuserprofile'),
        ),
    ]
